# A Python Lecture Series

## Lecture 2

#### by Luca Mingarelli

# Lecture 2
## Content:

   - I/O
   - Modules
   - NumPy and SciPy
   - Pandas

## Input/Output

To write in a file:

In [2]:
f = open('a_work_file', 'w')  # Opens the file workfile
# More specifically it creates a file object
f.write('This is a test\n')   
for n in range(5):
    f.write(str(n)+'\n')
f.close() 

In [3]:
import os
os.path.exists('a_work_file')

True

To read from a file:

In [4]:
f = open('a_work_file', 'r')
s = f.read()
print(s)
f.close()

This is a test
0
1
2
3
4



### Iterating over a file
For reading lines from a file, you can loop over the file object. This is memory efficient, fast, and leads to simple code.

In [5]:
f = open('a_work_file', 'r')
for line in f:
    print(line,end = '')
f.close()

This is a test
0
1
2
3
4


### File modes

   - Read-only: `r`
   - Write-only: `w`
     - Note: Create a new file or overwrite existing file.
   - Append to a file: `a`
   - Read and Write: `r+`
   - Binary mode: `b`

It is good practice to use the `with` keyword when dealing with file objects. The advantage is that the file is properly closed after its suite finishes, even if an exception is raised at some point (using `with` is also much shorter than writing equivalent try-finally blocks).

In [6]:
with open('A_new_test','w') as f:
    f.write('This is a NEW test\n\n')   
    for n in range(6):
        f.write(f'{n} squared is {n**2}\n') # A formatted string - notice the 'f' at the beginning of the string

In [7]:
with open('A_new_test','r') as f:
    print(f.read())

This is a NEW test

0 squared is 0
1 squared is 1
2 squared is 4
3 squared is 9
4 squared is 16
5 squared is 25



## Modules
#### i.e. how to write reusable code

A module is a file containing Python definitions and statements. The file name is the module name with the suffix `.py` appended.

In [8]:
%%writefile my_new_module.py

def a_complicated_function():
    print("Working... Done.")

Overwriting my_new_module.py


In [9]:
# import my_new_module as mnm
from my_new_module import a_complicated_function
a_complicated_function()

Working... Done.


In [10]:
os.makedirs('MODULES', exist_ok=True)

In [11]:
%%writefile MODULES/module2.py
def function2():
    print("Working... Done.")

Overwriting MODULES/module2.py


We could now call this as `MODULES.module2.function2`. However, to make our life easier we can instead write the following `__init__.py` file (notice the `.`!):

In [12]:
%%writefile MODULES/__init__.py
from .module2 import function2

Overwriting MODULES/__init__.py


In [13]:
import MODULES as MD
MD.function2()

Working... Done.


Most of the useful operations needed for scientific computing are contained within some module (e.g. **NumPy**, **SciPy**, etc.).

This means that in order to access them we will need to import that module as

- `import module`,

or giving it an alias as

- `import module as md`.

Then we will be able to call the function as `module.specific_function()` or as `md.specific_function()`. Alternatively we can import the required tool/function as

- `from module import specific_funtion`.

## NumPy and its arrays

**NumPy** provides an efficient extension package to Python for multidimensional arrays.

In [14]:
import numpy as np
x = np.array([1,2,3])
# Convert list to numpy array object
x

array([1, 2, 3])

In [15]:
###--- Notice that
x+x
###--- More on this later.

array([2, 4, 6])

In [16]:
x = np.linspace(0,10,11) # as in Matlab!
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
x = np.arange(1.5,10,2) # same as Matlab's [1.5:2:10]
x

array([1.5, 3.5, 5.5, 7.5, 9.5])

#### NumPy's number types and associated risk (overflow)

In [18]:
x=np.array([0,1])
print("x =",x,"and has dtype", x.dtype)

x = [0 1] and has dtype int64


In [19]:
x=np.array([0,1], dtype = np.int8)
x[:] = 2**7-1
print("x =",x,"and has dtype",x.dtype)

x = [127 127] and has dtype int8


In [20]:
print("x + 1 =",x + 1,"\t (because dtype is"
      ,x.dtype,"!)")

x + 1 = [-128 -128] 	 (because dtype is int8 !)


In [21]:
x=np.array([2**63-1,2**63-1])
print("x[0] =",x[0],"and has dtype",x.dtype)
sum(x) 

x[0] = 9223372036854775807 and has dtype int64


/var/folders/mr/_y_c100s5j378qr8ddz_jnch0000gn/T/ipykernel_10168/1056964290.py:3: RuntimeWarning: overflow encountered in long_scalars
  sum(x)


-2

#### Some of NumPy arrays' attributes and methods

In [22]:
x.ndim

1

In [23]:
x.shape

(2,)

In [24]:
len(x)

2

In [25]:
x = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array

In [26]:
x.shape 

(2, 3)

In [27]:
x.mean() ## an ojbject's method

2.5

In [28]:
x.dtype  # data type

dtype('int64')

In [29]:
print("itemsize:", x.itemsize, "bytes")
print("nbytes:", x.nbytes, "bytes") 

itemsize: 8 bytes
nbytes: 48 bytes


#### Higher dimensional arrays

In [30]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.diag(range(1,5)) 

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### Indexing and Slicing

Recall: `x[start:stop:step]`; when any is omitted the default values are `start=0`, `stop=size`, `step=1`

In [34]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
print('x[0] = ', x[0])
print('x[1] = ', x[1])

x[0] =  [0 1 2]
x[1] =  [3 4 5]


In [36]:
x[0][-1]

2

In [37]:
x[0,-1]

2

In [38]:
x[:,::-1]

array([[2, 1, 0],
       [5, 4, 3]])

In [39]:
x[::-1,:]

array([[3, 4, 5],
       [0, 1, 2]])

In [40]:
## Notice the equivalence x[0] = x[0,:] for multidimensional arrays
print(x[0,:]) # first row of x
print(x[0])   # still first row of x

[0 1 2]
[0 1 2]


#### IMPORTANT 1: Be carefull about the datatype:

In [41]:
print('type: ',x.dtype)
x[:,:] = np.pi
x

type:  int64


array([[3, 3, 3],
       [3, 3, 3]])

In [42]:
y = x.astype(bool)
# y = y.astype(float)
print('type: ',y.dtype)
y[:,:] = np.pi
y

type:  bool


array([[ True,  True,  True],
       [ True,  True,  True]])

#### IMPORTANT 2: Slices return views, NOT copies!

In [43]:
x_slice = x[:2,:2]
x_slice  

array([[3, 3],
       [3, 3]])

In [44]:
x_slice[:] = 2
x

array([[2, 2, 3],
       [2, 2, 3]])

This behavior is quite useful: when working with large datasets, we can access and process pieces of these datasets without the need to copy the data.

#### Copying NumPy arrays

In [45]:
x[:] = 3
x_slice_copy = x[:2, :2].copy()
x_slice_copy

array([[3, 3],
       [3, 3]])

In [46]:
x_slice_copy[:] = 2
x

array([[3, 3, 3],
       [3, 3, 3]])

#### Reshaping

In [47]:
x = np.array([1, 2, 3])
# reshape to row vector
x.reshape((1, 3))

array([[1, 2, 3]])

In [48]:
# reshape to row vector
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

#### Concatenation

In [49]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
Z = np.concatenate([x, y])
Z

array([1, 2, 3, 4, 5, 6])

In [50]:
# for multidimensional arrays as well


np.concatenate([Z, Z])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

Although `np.vstack` and `np.hstack` might be clearer:


In [51]:
x = np.array([1, 2, 3])
Z = np.array([[4, 5, 6],
              [7, 8, 9]])
# vertically stack the arrays
np.vstack([x, Z]) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
# horizontally stack the arrays
y = np.array([[456],
              [789]])
np.hstack([Z, y])

array([[  4,   5,   6, 456],
       [  7,   8,   9, 789]])

Use `np.dstack` to stack arrays along higher dimensional axis.

#### Splitting

In [53]:
Z1 = np.vstack([x, Z]).reshape((9,))
print(Z1)
x, y, z = np.split(Z1,[3,5])
print(x,y,z)

[1 2 3 4 5 6 7 8 9]
[1 2 3] [4 5] [6 7 8 9]


In [54]:
Z = np.arange(16).reshape((4, 4))

print(Z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [55]:
upper, lower = np.vsplit(Z, [2])
print('Upper part:\n',upper)
print('-'*15)
print('Lower part: \n',lower)

Upper part:
 [[0 1 2 3]
 [4 5 6 7]]
---------------
Lower part: 
 [[ 8  9 10 11]
 [12 13 14 15]]


In [56]:
left, right = np.hsplit(Z, [2])
print('Left part:\n',left)
print('-'*15)
print('Right part:\n',right)

Left part:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
---------------
Right part:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


#### Operations on NumPy arrays

Whenever possible, avoid looping: it's slow!

Instead it is advisable to make use of **NumPy**'s built in functions. These are highly optimised and are applied elementwise.

In [57]:
x = np.arange(-5,5)
np.abs(x)

array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4])

In [58]:
x = np.linspace(1,2,1000)
%timeit [1/x[n] for n in range(len(x))]
%timeit 1/x

1.13 ms ± 185 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
16.4 µs ± 3.86 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


The most common functions (trigonometric, exponentials, logarithms, etc.) can be found within **NumPy**. More specialised functions on the other hand, can be found in **SciPy**, within the sub-module `scipy.special`:

In [59]:
from scipy import special
x = np.array([0.5, 1.])
print("Γ(x)=", special.gamma(x))
print("Β(x,2)=", special.beta(x, 2))
print("erf(x)=", special.erf(x))

Γ(x)= [1.77245385 1.        ]
Β(x,2)= [1.33333333 0.5       ]
erf(x)= [0.52049988 0.84270079]


More *special* mathematical functions can be found  [here](https://docs.scipy.org/doc/scipy/reference/special.html#module-scipy.special).

Even when computing aggregates: use NumPy's functions.

In [60]:
x = np.arange(1000)
%timeit sum(x)
%timeit x.sum()
%timeit np.sum(x)  # the same as above!

291 µs ± 60.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
12.6 µs ± 1.35 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
33.2 µs ± 11.4 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [61]:
%timeit max(x)
%timeit x.max()
%timeit np.max(x)  # the same as above!

228 µs ± 30.2 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
12 µs ± 1.34 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
11.6 µs ± 1.51 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Same for `max` and `min`.

These operations can also be done along one axis only:

In [62]:
print(Z)
print("\nSum columns:")
Z.sum(axis = 1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Sum columns:


array([ 6, 22, 38, 54])

In [63]:
print("Max along columns:")
print(Z.max(axis = 0 ))
print("\nMax along rows:")
print(Z.max(axis = 1 ))

Max along columns:
[12 13 14 15]

Max along rows:
[ 3  7 11 15]


#### A summary of available aggregation functions

|Function Name	|NaN-safe Version	|Description|
|---------------|-------------------|-----------|
|`np.sum	    `|`np.nansum	    `    |Compute sum of elements|
|`np.prod	    `|`np.nanprod	    `    |Compute product of elements|
|`np.mean	    `|`np.nanmean	    `    |Compute mean of elements|
|`np.std	    `|`np.nanstd	    `    |Compute standard deviation|
|`np.var	    `|`np.nanvar        `	|Compute variance|
|`np.min	    `|`np.nanmin	    `    |Find minimum value|
|`np.max	    `|`np.nanmax	    `    |Find maximum value|
|`np.argmin	    `|`np.nanargmin	    `|Find index of minimum value|
|`np.argmax	    `|`np.nanargmax	    `|Find index of maximum value|
|`np.median  	`|`np.nanmedian	    `|Compute median of elements|
|`np.percentile	`|`np.nanpercentile	`|Compute rank-based statistics of elements|
|`np.any	    `|N/A	            |    Evaluate whether any elements are true|
|`np.all	    `|N/A	            |    Evaluate whether all elements are true|

#### Boolean operations

In [64]:
x = np.array([1,2,3,4,5,6])
x>3

array([False, False, False,  True,  True,  True])

|Operator|	Equivalent function|	
|--------|---------------------|
|`==`	  |     ` np.equal	 ` |  
|`<	`     |   `np.less		` |   
|`>`	  |   `   np.greater`	|    
|`!=`	|`np.not_equal`|
| `<=`	|`np.less_equal`|
| `>=`	|`np.greater_equal`|

#### Masks

A boolean array can be used to index which element to extract from a second array:

In [65]:
print(x)
print(x>3)
x[x>3]

[1 2 3 4 5 6]
[False False False  True  True  True]


array([4, 5, 6])

#### Fancy indexing

In [66]:
l = np.array([1,2,3,4,5])
l[[0,2]]

array([1, 3])

In [67]:
l[[-1,0,-2]]

array([5, 1, 4])

Moreover:

In [68]:
ind = np.array([[3, 0],
                [4, 1]])
l[ind]

array([[4, 1],
       [5, 2]])

When using fancy indexing, the output has the same shape as the index.

#### Broadcasting

Broadcasting is a feature allowing for binary operations to be performed on arrays with different shapes.

In [69]:
x = np.array([0,1,2])
print(x+3)
print(x+np.array([3,3,3]))

[3 4 5]
[3 4 5]


In [70]:
M = np.ones((3, 3))
M+x

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [71]:
y = x.reshape((3,1))
print('y=\n',y)
print('-'*10)
print('x+y=\n',x+y)

y=
 [[0]
 [1]
 [2]]
----------
x+y=
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


#### Rules of Broadcasting:
![alt](./img/broadcasting.png)

In [72]:
%%capture
### Broadcasting explained
import numpy as np
from matplotlib import pyplot as plt
# Adapted from astroML: see http://www.astroml.org/book_figures/appendix/fig_broadcast_visual.html
#------------------------------------------------------------
# Draw a figure and axis with no boundary
fig = plt.figure(figsize=(6, 4.5), facecolor='w')
ax = plt.axes([0, 0, 1, 1], xticks=[], yticks=[], frameon=False)


def draw_cube(ax, xy, size, depth=0.4,
              edges=None, label=None, label_kwargs=None, **kwargs):
    """draw and label a cube.  edges is a list of numbers between
    1 and 12, specifying which of the 12 cube edges to draw"""
    if edges is None:
        edges = range(1, 13)

    x, y = xy

    if 1 in edges:
        ax.plot([x, x + size],
                [y + size, y + size], **kwargs)
    if 2 in edges:
        ax.plot([x + size, x + size],
                [y, y + size], **kwargs)
    if 3 in edges:
        ax.plot([x, x + size],
                [y, y], **kwargs)
    if 4 in edges:
        ax.plot([x, x],
                [y, y + size], **kwargs)

    if 5 in edges:
        ax.plot([x, x + depth],
                [y + size, y + depth + size], **kwargs)
    if 6 in edges:
        ax.plot([x + size, x + size + depth],
                [y + size, y + depth + size], **kwargs)
    if 7 in edges:
        ax.plot([x + size, x + size + depth],
                [y, y + depth], **kwargs)
    if 8 in edges:
        ax.plot([x, x + depth],
                [y, y + depth], **kwargs)

    if 9 in edges:
        ax.plot([x + depth, x + depth + size],
                [y + depth + size, y + depth + size], **kwargs)
    if 10 in edges:
        ax.plot([x + depth + size, x + depth + size],
                [y + depth, y + depth + size], **kwargs)
    if 11 in edges:
        ax.plot([x + depth, x + depth + size],
                [y + depth, y + depth], **kwargs)
    if 12 in edges:
        ax.plot([x + depth, x + depth],
                [y + depth, y + depth + size], **kwargs)

    if label:
        if label_kwargs is None:
            label_kwargs = {}
        ax.text(x + 0.5 * size, y + 0.5 * size, label,
                ha='center', va='center', **label_kwargs)

solid = dict(c='black', ls='-', lw=1,
             label_kwargs=dict(color='k'))
dotted = dict(c='black', ls='-', lw=0.5, alpha=0.5,
              label_kwargs=dict(color='gray'))
depth = 0.3

#------------------------------------------------------------
# Draw top operation: vector plus scalar
draw_cube(ax, (1, 10), 1, depth, [1, 2, 3, 4, 5, 6, 9], '0', **solid)
draw_cube(ax, (2, 10), 1, depth, [1, 2, 3, 6, 9], '1', **solid)
draw_cube(ax, (3, 10), 1, depth, [1, 2, 3, 6, 7, 9, 10], '2', **solid)

draw_cube(ax, (6, 10), 1, depth, [1, 2, 3, 4, 5, 6, 7, 9, 10], '5', **solid)
draw_cube(ax, (7, 10), 1, depth, [1, 2, 3, 6, 7, 9, 10, 11], '5', **dotted)
draw_cube(ax, (8, 10), 1, depth, [1, 2, 3, 6, 7, 9, 10, 11], '5', **dotted)

draw_cube(ax, (12, 10), 1, depth, [1, 2, 3, 4, 5, 6, 9], '5', **solid)
draw_cube(ax, (13, 10), 1, depth, [1, 2, 3, 6, 9], '6', **solid)
draw_cube(ax, (14, 10), 1, depth, [1, 2, 3, 6, 7, 9, 10], '7', **solid)

ax.text(5, 10.5, '+', size=12, ha='center', va='center')
ax.text(10.5, 10.5, '=', size=12, ha='center', va='center')
ax.text(1, 11.5, r'${\tt np.arange(3) + 5}$',
        size=12, ha='left', va='bottom')

#------------------------------------------------------------
# Draw middle operation: matrix plus vector

# first block
draw_cube(ax, (1, 7.5), 1, depth, [1, 2, 3, 4, 5, 6, 9], '1', **solid)
draw_cube(ax, (2, 7.5), 1, depth, [1, 2, 3, 6, 9], '1', **solid)
draw_cube(ax, (3, 7.5), 1, depth, [1, 2, 3, 6, 7, 9, 10], '1', **solid)

draw_cube(ax, (1, 6.5), 1, depth, [2, 3, 4], '1', **solid)
draw_cube(ax, (2, 6.5), 1, depth, [2, 3], '1', **solid)
draw_cube(ax, (3, 6.5), 1, depth, [2, 3, 7, 10], '1', **solid)

draw_cube(ax, (1, 5.5), 1, depth, [2, 3, 4], '1', **solid)
draw_cube(ax, (2, 5.5), 1, depth, [2, 3], '1', **solid)
draw_cube(ax, (3, 5.5), 1, depth, [2, 3, 7, 10], '1', **solid)

# second block
draw_cube(ax, (6, 7.5), 1, depth, [1, 2, 3, 4, 5, 6, 9], '0', **solid)
draw_cube(ax, (7, 7.5), 1, depth, [1, 2, 3, 6, 9], '1', **solid)
draw_cube(ax, (8, 7.5), 1, depth, [1, 2, 3, 6, 7, 9, 10], '2', **solid)

draw_cube(ax, (6, 6.5), 1, depth, range(2, 13), '0', **dotted)
draw_cube(ax, (7, 6.5), 1, depth, [2, 3, 6, 7, 9, 10, 11], '1', **dotted)
draw_cube(ax, (8, 6.5), 1, depth, [2, 3, 6, 7, 9, 10, 11], '2', **dotted)

draw_cube(ax, (6, 5.5), 1, depth, [2, 3, 4, 7, 8, 10, 11, 12], '0', **dotted)
draw_cube(ax, (7, 5.5), 1, depth, [2, 3, 7, 10, 11], '1', **dotted)
draw_cube(ax, (8, 5.5), 1, depth, [2, 3, 7, 10, 11], '2', **dotted)

# third block
draw_cube(ax, (12, 7.5), 1, depth, [1, 2, 3, 4, 5, 6, 9], '1', **solid)
draw_cube(ax, (13, 7.5), 1, depth, [1, 2, 3, 6, 9], '2', **solid)
draw_cube(ax, (14, 7.5), 1, depth, [1, 2, 3, 6, 7, 9, 10], '3', **solid)

draw_cube(ax, (12, 6.5), 1, depth, [2, 3, 4], '1', **solid)
draw_cube(ax, (13, 6.5), 1, depth, [2, 3], '2', **solid)
draw_cube(ax, (14, 6.5), 1, depth, [2, 3, 7, 10], '3', **solid)

draw_cube(ax, (12, 5.5), 1, depth, [2, 3, 4], '1', **solid)
draw_cube(ax, (13, 5.5), 1, depth, [2, 3], '2', **solid)
draw_cube(ax, (14, 5.5), 1, depth, [2, 3, 7, 10], '3', **solid)

ax.text(5, 7.0, '+', size=12, ha='center', va='center')
ax.text(10.5, 7.0, '=', size=12, ha='center', va='center')
ax.text(1, 9.0, r'${\tt np.ones((3,\, 3)) + np.arange(3)}$',
        size=12, ha='left', va='bottom')

#------------------------------------------------------------
# Draw bottom operation: vector plus vector, double broadcast

# first block
draw_cube(ax, (1, 3), 1, depth, [1, 2, 3, 4, 5, 6, 7, 9, 10], '0', **solid)
draw_cube(ax, (1, 2), 1, depth, [2, 3, 4, 7, 10], '1', **solid)
draw_cube(ax, (1, 1), 1, depth, [2, 3, 4, 7, 10], '2', **solid)

draw_cube(ax, (2, 3), 1, depth, [1, 2, 3, 6, 7, 9, 10, 11], '0', **dotted)
draw_cube(ax, (2, 2), 1, depth, [2, 3, 7, 10, 11], '1', **dotted)
draw_cube(ax, (2, 1), 1, depth, [2, 3, 7, 10, 11], '2', **dotted)

draw_cube(ax, (3, 3), 1, depth, [1, 2, 3, 6, 7, 9, 10, 11], '0', **dotted)
draw_cube(ax, (3, 2), 1, depth, [2, 3, 7, 10, 11], '1', **dotted)
draw_cube(ax, (3, 1), 1, depth, [2, 3, 7, 10, 11], '2', **dotted)

# second block
draw_cube(ax, (6, 3), 1, depth, [1, 2, 3, 4, 5, 6, 9], '0', **solid)
draw_cube(ax, (7, 3), 1, depth, [1, 2, 3, 6, 9], '1', **solid)
draw_cube(ax, (8, 3), 1, depth, [1, 2, 3, 6, 7, 9, 10], '2', **solid)

draw_cube(ax, (6, 2), 1, depth, range(2, 13), '0', **dotted)
draw_cube(ax, (7, 2), 1, depth, [2, 3, 6, 7, 9, 10, 11], '1', **dotted)
draw_cube(ax, (8, 2), 1, depth, [2, 3, 6, 7, 9, 10, 11], '2', **dotted)

draw_cube(ax, (6, 1), 1, depth, [2, 3, 4, 7, 8, 10, 11, 12], '0', **dotted)
draw_cube(ax, (7, 1), 1, depth, [2, 3, 7, 10, 11], '1', **dotted)
draw_cube(ax, (8, 1), 1, depth, [2, 3, 7, 10, 11], '2', **dotted)

# third block
draw_cube(ax, (12, 3), 1, depth, [1, 2, 3, 4, 5, 6, 9], '0', **solid)
draw_cube(ax, (13, 3), 1, depth, [1, 2, 3, 6, 9], '1', **solid)
draw_cube(ax, (14, 3), 1, depth, [1, 2, 3, 6, 7, 9, 10], '2', **solid)

draw_cube(ax, (12, 2), 1, depth, [2, 3, 4], '1', **solid)
draw_cube(ax, (13, 2), 1, depth, [2, 3], '2', **solid)
draw_cube(ax, (14, 2), 1, depth, [2, 3, 7, 10], '3', **solid)

draw_cube(ax, (12, 1), 1, depth, [2, 3, 4], '2', **solid)
draw_cube(ax, (13, 1), 1, depth, [2, 3], '3', **solid)
draw_cube(ax, (14, 1), 1, depth, [2, 3, 7, 10], '4', **solid)

ax.text(5, 2.5, '+', size=12, ha='center', va='center')
ax.text(10.5, 2.5, '=', size=12, ha='center', va='center')
ax.text(1, 4.5, r'${\tt np.arange(3).reshape((3,\, 1)) + np.arange(3)}$',
        ha='left', size=12, va='bottom')

ax.set_xlim(0, 16)
ax.set_ylim(0.5, 12.5)

fig.savefig('img/broadcasting.png',dpi=150)

### Copy NumPy arrays (Deep-copy)

In [73]:
A = np.arange(10)
B = A
B[0]= 100
A

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [74]:
A = np.arange(10)
B = A.copy()
B[0]=100
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Pandas

### Main data structures in Pandas:
- Series
- DataFrames

### Series

In [75]:
import pandas as pd
pd.Series([0.1, 0.2, 0.3, 0.4, 0.5])

0    0.1
1    0.2
2    0.3
3    0.4
4    0.5
dtype: float64

In [76]:
s = pd.Series([0.1, 0.2, 0.3, 0.4, 0.5], 
       index = ['a','b','c','d','e'])
s['a'] #s[0] s['a'] s[s>2] s[:2] s[[3,4]]
##i.e. can be treated as nparrays

0.1

#### Be careful however about operations between different Series

In [77]:
s1 = pd.Series({'a': 0.1, 'b': 1.2, 'c': 2.3})
s2 = pd.Series({'a': 1.0, 'b': 2.0, 'c': 3.0})
s3 = pd.Series({'c': 0.1, 'd': 1.2, 'e': 2.3})

In [78]:
s1 + s2

a    1.1
b    3.2
c    5.3
dtype: float64

In [79]:
s1 + s3

a    NaN
b    NaN
c    2.4
d    NaN
e    NaN
dtype: float64

In [80]:
s1 = pd.Series([1,2,3],index=['a'] * 3)
s2 = pd.Series([4,5],index=['a'] * 2)
s1 + s2 #for non-unique indices: broadcasting to all common indices.

a    5
a    6
a    6
a    7
a    7
a    8
dtype: int64

#### It is possible to access the underlying arrays through the attributes `values` and `index`

In [81]:
print(type(s3.values))
s3.values

<class 'numpy.ndarray'>


array([0.1, 1.2, 2.3])

In [82]:
s3.index = ['First', 'Second', 'Third']
print(s3)
s3.index[1]

First     0.1
Second    1.2
Third     2.3
dtype: float64


'Second'

In [83]:
s = pd.Series([10,20,30], 
              index=[13,2,89])
## Now indexing is ambiguous!
s[2]
# s[0]  # Error

20

In [84]:
s.iloc[0:2] ## s.iloc[0:2] ##i.e. slicing works

13    10
2     20
dtype: int64

In [85]:
s.loc[89] # s.loc[[13,89]] 
##i.e. fancy indexing works

30

### Notable Methods of the `Series` data structure
#### Accessed as `my_series.method()`


| Name | Description |
|-- | -- |
| `head()` and `tail()` | Display the first five and the last five rows respectively (first/last $n$ rows if $n$ is given as an argument) |
| `isnull()` | Returns a Series with same indices and boolean values indicating where the values are  `NaNs` or `Null`s |
| `notnull()` | Negation of `isnull()`|
| `iloc()` | Access integer location of a Series|
| `loc()` | Access location according to indexing of the Series|
| `describe()` | Returns summary and statistics of the Series|
| `unique()` | Returns the unique elements of a Series|
| `drop(index)` |Drops elements with the selected index|
| `dropna()` | Drops all `NaN`s and `Null`s elements|
| `fillna(value)` |Fills all `NaN`s and `Null`s with `value` |
| `append(series)` |Appends a Series to another Series|


### DataFrame

Dataframes are a collection of `Series`.

In [86]:
df = pd.DataFrame(np.array([[1,2],[3,4]])) 
df

0  1
0  1  2
1  3  4

In [87]:
df.columns = ['col1','col2']
df.index = ['row1','row2']
df

col1  col2
row1     1     2
row2     3     4

In [88]:
pd.DataFrame(np.array([[1,2],[3,4]]),columns=['col1','col2'], index = ['row1','row2'])

col1  col2
row1     1     2
row2     3     4

In [89]:
s1 = pd.Series(np.arange(0,5))
s2 = pd.Series(np.arange(1,4))
s3 = pd.Series(np.arange(2,3))
pd.DataFrame({'col1': s1, 'col2': s2, 'col3': s3})

col1  col2  col3
0     0   1.0   2.0
1     1   2.0   NaN
2     2   3.0   NaN
3     3   NaN   NaN
4     4   NaN   NaN

In [90]:
df = pd.DataFrame({'col'+str(1+ i):pd.Series(np.arange(i,5.0-i)) for i in range(3)})#np.random.randint(0,3,3)

In [91]:
df.describe()

col1  col2  col3
count  5.000000   3.0   1.0
mean   2.000000   2.0   2.0
std    1.581139   1.0   NaN
min    0.000000   1.0   2.0
25%    1.000000   1.5   2.0
50%    2.000000   2.0   2.0
75%    3.000000   2.5   2.0
max    4.000000   3.0   2.0

In [92]:
df.sum() ### NaN automatically diregarded!

col1    10.0
col2     6.0
col3     2.0
dtype: float64

#### Selecting columns ...

In [93]:
print(df['col1'])
print(type(df['col1']))

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
Name: col1, dtype: float64
<class 'pandas.core.series.Series'>


In [94]:
print(df[['col1','col3']])
print(type(df[['col1','col3']]))

   col1  col3
0   0.0   2.0
1   1.0   NaN
2   2.0   NaN
3   3.0   NaN
4   4.0   NaN
<class 'pandas.core.frame.DataFrame'>


#### ... selecting rows...

In [95]:
df[2:4] 

col1  col2  col3
2   2.0   3.0   NaN
3   3.0   NaN   NaN

#### ...and of course: selecting rows and columns...

In [96]:
df[2:4][['col2']]

col2
2   3.0
3   NaN

#### ...deleting columns...

In [97]:
df2 = df.copy() #Recall the `issue` in numpy?
del df2['col2']
df2

col1  col3
0   0.0   2.0
1   1.0   NaN
2   2.0   NaN
3   3.0   NaN
4   4.0   NaN

In [98]:
df2.pop('col1')

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
Name: col1, dtype: float64

In [99]:
df2

col3
0   2.0
1   NaN
2   NaN
3   NaN
4   NaN

In [100]:
df2 = df.drop(['col1','col3'],axis = 1)
df2

col2
0   1.0
1   2.0
2   3.0
3   NaN
4   NaN

In [101]:
df

col1  col2  col3
0   0.0   1.0   2.0
1   1.0   2.0   NaN
2   2.0   3.0   NaN
3   3.0   NaN   NaN
4   4.0   NaN   NaN

### Data import with Pandas

#### [CSV files](pandas.read_csv)
Comma-separated value files can be easily read using `pandas.read_csv`:

`csv_data = pd.read_csv('file.csv')`

#### [Exel files](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html)

`csv_data = pd.read_excel('file.xlsx')`

`pandas.read_excel` requires two arguments: the name of the file and the name of the sheet.

Moreover, more optional arguments can be parsed to these functions to specify where to start reading from, how many rows to read, etc.

Additionally, `pd.read_stata`, `pd.read_sql`, `pd.read_json`, [and more](https://pandas.pydata.org/pandas-docs/stable/reference/io.html)

### What to do with missing data?

- `None` Missing data inside of dataframe of type `object`
- `NaN` Missing numerical data

In [102]:
# None + 1
np.nan +1

nan

In [103]:
pd.Series([1, np.nan, 2, None])
## Notice both the mapping None -> NaN
## as well as int -> float

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

#### Detection of missing data

In [104]:
df.count() #count non-missing elements

col1    5
col2    3
col3    1
dtype: int64

In [105]:
df.notnull() # opposite: df.isnull()

col1   col2   col3
0  True   True   True
1  True   True  False
2  True   True  False
3  True  False  False
4  True  False  False

In [106]:
df['col2'][df['col2'].notnull()]

0    1.0
1    2.0
2    3.0
Name: col2, dtype: float64

#### Dropping missing values

In [107]:
df.dropna() 
## drops all rows 
## with at least one missing value

col1  col2  col3
0   0.0   1.0   2.0

In [108]:
df.dropna(axis='columns')

col1
0   0.0
1   1.0
2   2.0
3   3.0
4   4.0

#### Filling missing values

In [109]:
df.fillna(0)
df

col1  col2  col3
0   0.0   1.0   2.0
1   1.0   2.0   NaN
2   2.0   3.0   NaN
3   3.0   NaN   NaN
4   4.0   NaN   NaN

In [110]:
# forward-fill
df.fillna(method='ffill') #bfill for back-fill

col1  col2  col3
0   0.0   1.0   2.0
1   1.0   2.0   2.0
2   2.0   3.0   2.0
3   3.0   3.0   2.0
4   4.0   3.0   2.0

In [111]:
# change axis
df.fillna(method='ffill',axis = 1)

col1  col2  col3
0   0.0   1.0   2.0
1   1.0   2.0   2.0
2   2.0   3.0   3.0
3   3.0   3.0   3.0
4   4.0   4.0   4.0

In [112]:
df = pd.DataFrame({"A":[12, 4, 5, None, 1], 
                   "B":[None, 2, 54, 3, None], 
                   "C":[20, 16, None, 3, 8], 
                   "D":[14, 3, None, None, 6]}) 
df

A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   NaN   NaN
3   NaN   3.0   3.0   NaN
4   1.0   NaN   8.0   6.0

In [113]:
# to interpolate the missing values 
df.interpolate(method ='linear', limit_direction ='forward',axis = 1) 

A     B     C     D
0  12.0  16.0  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0  54.0  54.0
3   NaN   3.0   3.0   3.0
4   1.0   4.5   8.0   6.0

Alternatively:
- `linear`: Ignore the index and treat the values as equally spaced.
- `time`: Works on daily and higher resolution data to interpolate given length of interval.
- `index`, `values`: use the actual numerical values of the index.
- `pad`: Fill in `NaN`s using existing values.
- `nearest`, `zero`, `slinear`, `quadratic`, `cubic`, `spline`, `barycentric`, `polynomial`
- `krogh`, `piecewise_polynomial`, `spline`, `pchip`, `akima`

[More here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.interpolate.html).

## Probability and Statistics

### Random generators

In [114]:
import random as rnd
rnd.random() ## Uniform in [0,1)

0.7702406177134812

In [115]:
# uniform in range
rnd.uniform(1,10) 

8.510297287826479

In [116]:
#simulate die
rnd.randint(1,6)

6

In [117]:
greetings = ['Hi', 'Hello', 'Welcome!', 'Hola']
rnd.choice(greetings)

'Hello'

In [118]:
#Simulate wheel spins
colors = ['R', 'B', 'G'] # Red, Black and Green
rnd.choices(colors, weights=[18,18,2] ,k =10)

['R', 'R', 'R', 'R', 'B', 'B', 'R', 'B', 'B', 'R']

In [119]:
# Shuffle cards
deck = list(range(1,53)) ## 52 cards
rnd.shuffle(deck)
print(deck)

[31, 33, 29, 35, 9, 16, 8, 34, 47, 2, 18, 23, 19, 42, 3, 15, 5, 6, 30, 48, 10, 13, 50, 25, 17, 44, 7, 49, 4, 36, 20, 22, 26, 41, 14, 32, 27, 37, 51, 45, 43, 28, 24, 52, 1, 40, 46, 21, 12, 11, 39, 38]


In [120]:
#Sample a hand from the deck
hand = rnd.sample(deck,k=5)
print(hand)## only unique values

[43, 38, 12, 27, 36]


#### NumPy random generators

In [121]:
 import numpy.random as rnd

In [122]:
## UNIFORM
print(rnd.rand(3,4)) 

[[0.9736172  0.52520565 0.19762005 0.89531565]
 [0.11478142 0.68405472 0.04304964 0.19013752]
 [0.97956814 0.78129814 0.85602995 0.99524693]]


In [123]:
## STANDARD NORMAL
print(rnd.randn(3,4))

[[-0.378791   -0.47537559  0.18065412  0.08813969]
 [ 0.06175533  0.06827654 -1.01927363 -1.41061102]
 [-1.40217787 -0.78883006  0.32066356  0.13660369]]


In [124]:
## UNIFORM INTEGERS
print(rnd.randint(0,100,(3,4)))

[[86 49  5 13]
 [29  4 59 14]
 [44 77 97 91]]


In [125]:
rnd.shuffle(deck)
print(deck)

[3, 38, 20, 28, 27, 41, 47, 6, 8, 51, 22, 32, 12, 26, 35, 52, 9, 46, 1, 19, 49, 24, 10, 33, 21, 23, 50, 4, 48, 29, 31, 2, 36, 43, 25, 16, 14, 18, 44, 40, 5, 13, 42, 45, 37, 17, 7, 39, 15, 11, 30, 34]


|Function|Description|
|--|--|
|`uniform(a,b,k)`|Returns $k$ draws from $U(a,b)$.|
|`normal(μ,σ,k)`|Returns $k$ draws from $\mathcal{N}(\mu,\sigma)$.|
|`multivariate_normal(μ,Σ,k)`|Returns $k$ draws from $\mathcal{N}(\vec{\mu},\Sigma)$.|
|`lognormal(μ,σ,k)`|Returns $k$ draws from $\text{LogNormal}(\mu,\sigma)$.|
|`standard_t(ν,k)`|Returns $k$ draws from $\text{Student-t}(\nu)$.|
|`chisquare(nu,k)`| Returns $k$ draws from $\chi_\nu^2$.  | 
|`poisson(λ,k)`|Returns $k$ draws from $\text{Poisson}(\lambda)$.|
|`binomial(n,p,k)`| Returns $k$ draws from $B(n,p)$.| 
|`binomial(1,p,k)`| Returns $k$ draws from $\text{Bernoulli}(p)$.| 
|`multinomial(n,p,k)`|Returns $k$ draws from $\text{Multinomial}(n,\vec{p})$ (`n` trials, and a list of probabilities `p`).|
|`exponential(λ,k)`|Returns $k$ draws from $\text{Exponential}(\lambda)$. | 
|`f(ν1,ν2,k)`|Returns $k$ draws from $F_{\nu_1,\nu_2}$.|
|`gamma(α,θ,k)`|Returns $k$ draws from $\Gamma(\alpha,\theta)$ ($\alpha$ and $\theta$ the shape and scale parameters).|
|and more...|...|

Note 1: call as `rnd.function_name(...)`.

Note 2: the argument `k` is optional.

Note 3: replace `k` with `(k,l)` to obtain a $k\times l$ matrix instead.

### More advanced statistical analysis packages

- [statsmodels](http://www.statsmodels.org/stable/index.html): mainly to estimate statistical models, and perform statistical tests. Includes: Linear Regression, Generalized Linear Models, Generalized Estimating Equations, Robust Linear Models, Linear Mixed Effects Models, Regression with Discrete Dependent Variables, ANOVA, Time Series analysis, Models for Survival and Duration Analysis, Statistics (e.g. Multiple Tests, Sample Size Calculations etc.), Nonparametric Methods, Generalized Method of Moments, Empirical Likelihood, ...

- [PyMC](http://pymc-devs.github.io/pymc/): for Bayesian statistical models and fitting algorithms, including MCMC and Gaussian Processes. 

- [scikit-learn](https://scikit-learn.org/stable/): for machine learning, data mining, and data analysis, including supervised and unsupervised learning. Includes tools for: Classification , Regression , Clustering , Dimensionality reduction , Model selection.

# End of Lecture 2